### ISSUE TITLE
Correction P4

### ISSUE THREAD

**Issue by lecascyril** [MaxVast/maintenance-auto-web3#1]
Très belle utilisation de l'ERC5192, d'ERC721 ainsi que de l'ERC20 ! Code très propre et très bien documenté, scripts pertinents et très bon tests, rien à redire au niveau du backend qui est très bien maîtrisé. Le front-end est aussi très qualitatif, autant au niveau de l'architecture que de la qualité du code en lui-même. Belle utilisation des contexts, les clés sont bien sécurisées (.env). Le dossier './components' est particulièrement bien factorisé et organisé. Dommage que l'UI ne soit pas au top, sinon ça aurait été un projet parfait. Bravo pour ce très beau travail ! 
9,5

**Comment by MaxVast** [comment]
Merci @lecascyril pour ce retour qui me fait énormément plaisir ! 💯
